### PR TITLE
Fix missing properties on WebSocket MessageEvent

### LINKED ISSUE #836: Snaps Websockets message doesn't contain data
Snaps Websocket implementation doesn't have data.
The tests check this, but seems it doesn't work in Snap env.

```typescript
const ws = new Websocket("ws://asd");
ws.onmesssage = (ev) => {
  assert(ev.data !== undefined);
}
```

cc @tetratorus

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes missing properties on WebSocket MessageEvent. We were spreading the object instead of navigating the prototype chain to look for the properties, as such, not all properties were correctly copied to the event.

Fixes #836

### CODE REVIEW

File: packages/execution-environments/src/common/endowments/network.ts [hunk 1]
```diff
@@ -396,19 +396,29 @@ const createNetwork = () => {
...
-            ...functions,
-            target: this,
-            currentTarget: this,
-            srcElement: this,
-            ports: [this],
-            source: null,
-            composedPath: () => [this],
-          },
-        ]);
+        // TODO: Should we migrate this to use a wrapper class?
```
Comment (FrederikBolding) [inline packages/execution-environments/src/common/endowments/network.ts:399]: We could replace this entire thing with a wrapper class same as we do for responses 🤔

File: packages/execution-environments/src/common/endowments/network.ts [hunk 2]
```diff
@@ -396,19 +396,29 @@ const createNetwork = () => {
...
+        const properties = [...allProperties(e)]
```
Comment (Mrtenz) [inline packages/execution-environments/src/common/endowments/network.ts:400]: Why are you creating a copy of the properties?

Comment (FrederikBolding) [reply packages/execution-environments/src/common/endowments/network.ts:400]: You cannot use `reduce` directly on a `Set`

**Review by Mrtenz — APPROVED** [review]
