### PR TITLE
Fix Webpack plugin issue with existing files

### LINKED ISSUE #811: Webpack plugin not updating version in manifest
When cutting `0.22.0` I discovered that the Webpack example doesn't update its manifest to match `package.json` when I run `yarn build` in the root. It does work on CI, which is how I caught the error, but locally for me it is broken.

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes an issue where already built files would be ignored by the Webpack plugin. This was fixed by using another hook to capture the emit (`afterEmit`), since the previous hook would not be called if the output file already existed.

Fixes #811

### CODE REVIEW

File: packages/plugin-webpack/src/plugin.ts [hunk 1]
```diff
@@ -80,43 +82,48 @@ export default class SnapsWebpackPlugin {
...
-            this.options.writeManifest,
-            content.toString('utf-8'),
+      if (this.options.manifestPath) {
+        const { errors, warnings } = await checkManifest(
+          pathUtils.dirname(this.options.manifestPath),
+          this.options.writeManifest,
+          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+          (await promisify(compiler.outputFileSystem.readFile)(
+            filePath,
+          ))!.toString(),
```
Comment (Mrtenz) [inline packages/plugin-webpack/src/plugin.ts:108]: Can probably be an assertion too.

**Review by Mrtenz — CHANGES_REQUESTED** [review]

**Review by Mrtenz — APPROVED** [review]
